error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:27:26
   |
LL |     with_none_and_format.expect(&format!("Error {}: fake error", error_code));
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("Error {}: fake error", error_code))`
   |
   = note: `-D clippy::expect-fun-call` implied by `-D warnings`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:30:26
   |
LL |     with_none_and_as_str.expect(format!("Error {}: fake error", error_code).as_str());
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("Error {}: fake error", error_code))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:40:25
   |
LL |     with_err_and_format.expect(&format!("Error {}: fake error", error_code));
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| panic!("Error {}: fake error", error_code))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:43:25
   |
LL |     with_err_and_as_str.expect(format!("Error {}: fake error", error_code).as_str());
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| panic!("Error {}: fake error", error_code))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:58:17
   |
LL |     Some("foo").expect({ &format!("error") });
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| { let msg = { &format!("error") }; panic!(msg) }))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:59:17
   |
LL |     Some("foo").expect(format!("error").as_ref());
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("error"))`

error: aborting due to 6 previous errors

